### ISSUE TITLE
Change deepcopy in deprecation testing to avoid "TypeError"

### ISSUE THREAD

**Issue by bool-dev** [e-dard/flask-s3#50]
While trying out the latest 0.2.7 version. I ran into this error:

`TypeError: object.__new__(NotImplementedType) is not safe, use NotImplementedType.__new__()`

Resulting from the `deepcopy()` within `_test_deprecation`. Probably because I have imported some modules in my config, and the standard deepcopy doesn't know what to do for them.

Maybe this could be changed?
Not really needed to copy the config, since the code directly changes the `app.config`. Moreover we don't really need to loop through all the config keys since we are interested only in flask-s3 specific keys.

**Comment by SunDwarf** [comment]
Closed by #51
