### ISSUE TITLE
Not all files should be gzipped

### ISSUE THREAD

**Issue by bool-dev** [e-dard/flask-s3#55]
According to some credible sources, certain files should not be gzipped, as there is hardly any gain, and sometimes it could in fact bloat the file.

Some sources:
* [Question on webmasters.stackexchange.com](http://webmasters.stackexchange.com/questions/8382/gzipped-images-is-it-worth)
* [Google Developers Article] (https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer?hl=en#text-compression-with-gzip)

So IMHO there should be a config variable to limit gzipping to certain files only. I am ready with a solution, will be adding a pull-request soon.

**Comment by SunDwarf** [comment]
Closed in #56, hopefully

**Comment by bool-dev** [comment]
:smiley: I will try and add tests for `gzip` and `gzip_only_exts` over the weekend.

So just confirming, mock calls are the best way to test for calls within functions? (since all of that is happening with more calls within `_write_files`)

_(i don't write tests for my project currently, so un familiar with the best approaches)_
