### ISSUE TITLE
Support for versioning and prefixing

### ISSUE THREAD

**Issue by virtosubogdan** [e-dard/flask-s3#63]
There should be an option to augment the prefix for static files.
This should be done by a static prefix and a dynamic option (for versioning).

The use case for the static prefix is that a bucket contains a lot of resources for many applications/environments.
It seems similar to https://github.com/e-dard/flask-s3/issues/22, but because the static file location does not depend at all on the application logic, this is completely different. 
The static files should be collected to `/path_to_allowed_prefix/environment/static_files` on the S3 bucket, where `/path_to_allowed_prefix/environment/` should be specified by a setting.

The use case for versioning is the standard one. Appending a hash to the filename is an alternative, but the choice between hash appending and another prefix should be up to the flask-s3 user.
The proposition is to do this by another setting which will contain the path to the function where the user implements the versioning prefix.

All requests should add no overhead when collecting or using `url_for` for users that do not want to use them.

**Comment by SunDwarf** [comment]
Closed by #64
