### ISSUE TITLE
Switch to best-effort for setting bucket ACL

### ISSUE THREAD

**Issue by virtosubogdan** [e-dard/flask-s3#65]
The credentials used for static file collection may lack the rights to do the operation: `s3.put_bucket_acl(Bucket=bucket_name, ACL='public-read'`
This happens when credentials are created with minimum required rights and bucket setting ACL does not seem to be required. For each static file uploaded, the public policy is also set and that should be enough.

I have read https://github.com/e-dard/flask-s3/issues/16 and https://github.com/e-dard/flask-s3/pull/24.
This issue is related, but at least to me, seems different.

I propose that this operation is treated as a best-effort to set it (ignoring fails caused by insufficient rights) or a setting is added for this purpose.

**Comment by SunDwarf** [comment]
Closed with #66
