### ISSUE TITLE
Latest release 0.2.13 do not defines default values for configuration keys

### ISSUE THREAD

**Issue by dappiu** [e-dard/flask-s3#71]
I received an update from pip for Flask-S3 from 0.2.8 to 0.2.13 but there are some strange things going on and I don't think the release should be kept there.

For example, from the documentation is missing content on the section *Flask-S3 Options*, and also the code don't have default values for configuration keys (all of them, I kept receiving `KeyError: 'FLASKS3_*'` until I declared all of them in my config file).

I just downgraded to 0.2.8 but I think it's best to remove this faulty release, or to fix it.

Thanks!

**Comment by SunDwarf** [comment]
Huh, this must be a regression since that ver.

I'll probably have a chance to fix it tommorow; until then stay on 0.2.8.

**Comment by SunDwarf** [comment]
A bit late on, this, but I can't reproduce this.

```
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>> import flask_s3
>>> app = flask.Flask("test")
>>> s3 = flask_s3.FlaskS3()
>>> s3.init_app(app)
>>> app.config["FLASKS3_USE_HTTPS"]
True
```

The defaults appear to be there on this simple example.

**Comment by dappiu** [comment]
I'm sorry if I raised a false alarm, there must be something wrong with my
virtualenv: I just tried initializing two new virtualenvs, with python 2.7
and 3.5 and with the simple snippet you posted I have no trouble at all, on
my old virtualenv I keep getting KeyError, can't figure out why.

Pardon. But still the latest documentation is missing the list of available
configuration keys.

Regards,
DR

2016-05-30 12:13 GMT+02:00 Isaac Dickinson <notifications@github.com>:

> A bit late on, this, but I can't reproduce this.
>
> Python 3.5.1 (default, Mar  3 2016, 09:29:07)
> [GCC 5.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import flask
> >>> import flask_s3
> >>> app = flask.Flask("test")
> >>> s3 = flask_s3.FlaskS3()
> >>> s3.init_app(app)
> >>> app.config["FLASKS3_USE_HTTPS"]
> True
>
> The defaults appear to be there on this simple example.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/e-dard/flask-s3/issues/71#issuecomment-222460500>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACMhaoUO99tAAGFBIcaqA0jIFhLnkxgeks5qGrg3gaJpZM4IiFRa>
> .
>



-- 
Davide Rossi

GnuPG/PGP Key ID: 4AE92D78
FINGERPRINT: 33A1 9E37 C91A DDC7 0231 FDE1 AB8D 2D4A 4AE9 2D78
Server: pgp.mit.edu
