### ISSUE TITLE
Default settings: use `.get(…)` instead of brackets?

### ISSUE THREAD

**Issue by cuducos** [e-dard/flask-s3#75]
Hi all,

Thanks for creating and maintaining Flask-S3.

Maybe I'm doing something wrong (probably), but I had to [manually set the value of some settings to the default value](https://github.com/cuducos/cunhajacaiu/pull/2/commits/9e5e7a0513340f1587415189ceba36579a712f1e) in order to get version 0.3.0 to work.

I was getting `KeyError` exception when Flask-S3 tried to reach some values in `app.config` (e.g. [lines 96, 103 and 109](https://github.com/e-dard/flask-s3/blob/master/flask_s3.py#L96)).

I was considering send a PR using a `app.config.get(…)` instead of `app.config[…]` to avoid this exceptions — what do you think about it? May I or is there a reason to avoid that?

Many thanks,

**Comment by SunDwarf** [comment]
This must have been a small oversight not caught by the tests when I removed the deprecation tests or something...

A PR to fix this would be greatly appreciated - `.get()` would be better, definitely.

**Comment by cuducos** [comment]
Great! Gonna suggest something in a while ; )
