### ISSUE TITLE
Six.u UnicodeDecodeError

### ISSUE THREAD

**Issue by stevefan** [e-dard/flask-s3#80]
Using Windows 7 Professional

...\flask_s3.py", line 177, in _gather_files
    dirs = [(six.u(app.static_folder), app.static_url_path)]

...\flask_s3.py", line 177, in _gather_files
    dirs = [(six.u(app.static_folder), app.static_url_path)]

UnicodeDecodeError: 'unicodeescape' codec can't decode bytes in position
 2-3: truncated \UXXXXXXXX escape

Seems like how Flask handles storing Windows 7 paths isn't automatically compatible with how Six wants to convert to unicode.

**Comment by SunDwarf** [comment]
Windows paths should use double \ instead of a single one. 

```
>>> "C:\Users"
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
>>> "C:\\Users"
'C:\\Users'
```

**Comment by stevefan** [comment]
I'm going to have to review the context of my comment,
